---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.8.5
  values:
    hostNetwork:
      enabled: true
    args:
    - --v=2
    - --kubelet-preferred-address-types=InternalIP 
    - --deprecated-kubelet-completely-insecure
    - --kubelet-port=10255
