apiVersion: v1
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: gloo
      name: gloo
      options:
        path: /var/lib/grafana/dashboards/gloo
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: gloo
      type: prometheus
      url: http://glooe-prometheus-server:80
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
kind: ConfigMap
metadata:
  labels:
    app: glooe-grafana
    chart: grafana-4.0.1
    heritage: Helm
    release: glooe
  name: glooe-grafana
  namespace: gloo-system
