apiVersion: v1
data:
  DASHBOARD_JSON_TEMPLATE: "{\n  \"annotations\": {\n    \"list\": [\n      {\n  \
    \      \"builtIn\": 1,\n        \"datasource\": \"-- Grafana --\",\n        \"\
    enable\": true,\n        \"hide\": true,\n        \"iconColor\": \"rgba(0, 211,\
    \ 255, 1)\",\n        \"name\": \"Annotations & Alerts\",\n        \"type\": \"\
    dashboard\"\n      }\n    ]\n  },\n  \"description\": \"Envoy proxy monitoring\
    \ Dashboard with cluster and host level templates. \",\n  \"editable\": true,\n\
    \  \"graphTooltip\": 0,\n  \"uid\": \"{{.Uid}}\",\n  \"id\": null,\n  \"links\"\
    : [],\n  \"timezone\": \"\",\n  \"title\": \"{{.EnvoyClusterName}}\",\n  \"version\"\
    : 4,\n  \"panels\": [\n    {\n      \"aliasColors\": {},\n      \"bars\": false,\n\
    \      \"dashLength\": 10,\n      \"dashes\": false,\n      \"datasource\": \"\
    gloo\",\n      \"fill\": 1,\n      \"gridPos\": {\n        \"h\": 7,\n       \
    \ \"w\": 12,\n        \"x\": 0,\n        \"y\": 5\n      },\n      \"id\": 2,\n\
    \      \"legend\": {\n        \"avg\": false,\n        \"current\": false,\n \
    \       \"max\": false,\n        \"min\": false,\n        \"show\": true,\n  \
    \      \"total\": false,\n        \"values\": false\n      },\n      \"lines\"\
    : true,\n      \"linewidth\": 1,\n      \"links\": [],\n      \"nullPointMode\"\
    : \"null\",\n      \"percentage\": false,\n      \"pointradius\": 5,\n      \"\
    points\": false,\n      \"renderer\": \"flot\",\n      \"seriesOverrides\": [],\n\
    \      \"spaceLength\": 10,\n      \"stack\": false,\n      \"steppedLine\": false,\n\
    \      \"targets\": [\n        {\n          \"expr\": \"envoy_cluster_upstream_cx_active{\
    \ envoy_cluster_name=\\\"{{.EnvoyClusterName}}\\\" }\",\n          \"format\"\
    : \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\"\
    : \"{{.NameTemplate}}\",\n          \"refId\": \"A\"\n        }\n      ],\n  \
    \    \"thresholds\": [],\n      \"timeFrom\": null,\n      \"timeRegions\": [],\n\
    \      \"timeShift\": null,\n      \"title\": \"Total active connections\",\n\
    \      \"tooltip\": {\n        \"shared\": true,\n        \"sort\": 0,\n     \
    \   \"value_type\": \"individual\"\n      },\n      \"type\": \"graph\",\n   \
    \   \"xaxis\": {\n        \"buckets\": null,\n        \"mode\": \"time\",\n  \
    \      \"name\": null,\n        \"show\": true,\n        \"values\": []\n    \
    \  },\n      \"yaxes\": [\n        {\n          \"format\": \"short\",\n     \
    \     \"label\": null,\n          \"logBase\": 1,\n          \"max\": null,\n\
    \          \"min\": null,\n          \"show\": true\n        },\n        {\n \
    \         \"format\": \"short\",\n          \"label\": null,\n          \"logBase\"\
    : 1,\n          \"max\": null,\n          \"min\": null,\n          \"show\":\
    \ true\n        }\n      ],\n      \"yaxis\": {\n        \"align\": false,\n \
    \       \"alignLevel\": null\n      }\n    },\n    {\n      \"aliasColors\": {},\n\
    \      \"bars\": false,\n      \"dashLength\": 10,\n      \"dashes\": false,\n\
    \      \"datasource\": \"gloo\",\n      \"fill\": 1,\n      \"gridPos\": {\n \
    \       \"h\": 7,\n        \"w\": 12,\n        \"x\": 12,\n        \"y\": 5\n\
    \      },\n      \"id\": 4,\n      \"legend\": {\n        \"avg\": false,\n  \
    \      \"current\": false,\n        \"max\": false,\n        \"min\": false,\n\
    \        \"show\": true,\n        \"total\": false,\n        \"values\": false\n\
    \      },\n      \"lines\": true,\n      \"linewidth\": 1,\n      \"links\": [],\n\
    \      \"nullPointMode\": \"null\",\n      \"percentage\": false,\n      \"pointradius\"\
    : 5,\n      \"points\": false,\n      \"renderer\": \"flot\",\n      \"seriesOverrides\"\
    : [],\n      \"spaceLength\": 10,\n      \"stack\": false,\n      \"steppedLine\"\
    : false,\n      \"targets\": [\n        {\n          \"expr\": \"irate(envoy_cluster_upstream_rq_total{\
    \ envoy_cluster_name=\\\"{{.EnvoyClusterName}}\\\" }[1m])\",\n          \"format\"\
    : \"time_series\",\n          \"intervalFactor\": 2,\n          \"legendFormat\"\
    : \"{{.NameTemplate}}\",\n          \"refId\": \"A\"\n        }\n      ],\n  \
    \    \"thresholds\": [],\n      \"timeFrom\": null,\n      \"timeRegions\": [],\n\
    \      \"timeShift\": null,\n      \"title\": \"Total requests\",\n      \"tooltip\"\
    : {\n        \"shared\": true,\n        \"sort\": 0,\n        \"value_type\":\
    \ \"individual\"\n      },\n      \"type\": \"graph\",\n      \"xaxis\": {\n \
    \       \"buckets\": null,\n        \"mode\": \"time\",\n        \"name\": null,\n\
    \        \"show\": true,\n        \"values\": []\n      },\n      \"yaxes\": [\n\
    \        {\n          \"format\": \"short\",\n          \"label\": null,\n   \
    \       \"logBase\": 1,\n          \"max\": null,\n          \"min\": null,\n\
    \          \"show\": true\n        },\n        {\n          \"format\": \"short\"\
    ,\n          \"label\": null,\n          \"logBase\": 1,\n          \"max\": null,\n\
    \          \"min\": null,\n          \"show\": true\n        }\n      ],\n   \
    \   \"yaxis\": {\n        \"align\": false,\n        \"alignLevel\": null\n  \
    \    }\n    },\n    {\n      \"aliasColors\": {},\n      \"bars\": false,\n  \
    \    \"dashLength\": 10,\n      \"dashes\": false,\n      \"datasource\": \"gloo\"\
    ,\n      \"fill\": 1,\n      \"gridPos\": {\n        \"h\": 7,\n        \"w\"\
    : 12,\n        \"x\": 0,\n        \"y\": 19\n      },\n      \"id\": 15,\n   \
    \   \"legend\": {\n        \"avg\": false,\n        \"current\": false,\n    \
    \    \"max\": false,\n        \"min\": false,\n        \"show\": true,\n     \
    \   \"total\": false,\n        \"values\": false\n      },\n      \"lines\": true,\n\
    \      \"linewidth\": 1,\n      \"links\": [],\n      \"nullPointMode\": \"null\"\
    ,\n      \"percentage\": false,\n      \"pointradius\": 5,\n      \"points\":\
    \ false,\n      \"renderer\": \"flot\",\n      \"seriesOverrides\": [],\n    \
    \  \"spaceLength\": 10,\n      \"stack\": false,\n      \"steppedLine\": false,\n\
    \      \"targets\": [\n        {\n          \"expr\": \"irate(envoy_cluster_upstream_cx_rx_bytes_total{\
    \ envoy_cluster_name=\\\"{{.EnvoyClusterName}}\\\" }[1m])\",\n          \"format\"\
    : \"time_series\",\n          \"intervalFactor\": 1,\n          \"legendFormat\"\
    : \"{{.NameTemplate}} - in\",\n          \"refId\": \"A\"\n        },\n      \
    \  {\n          \"expr\": \"irate(envoy_cluster_upstream_cx_rx_bytes_total{ envoy_cluster_name=\\\
    \"{{.EnvoyClusterName}}\\\" }[1m])\",\n          \"format\": \"time_series\",\n\
    \          \"intervalFactor\": 1,\n          \"legendFormat\": \"{{.NameTemplate}}\
    \ - out\",\n          \"refId\": \"B\"\n        }\n      ],\n      \"thresholds\"\
    : [],\n      \"timeFrom\": null,\n      \"timeRegions\": [],\n      \"timeShift\"\
    : null,\n      \"title\": \"Upstream Network Traffic\",\n      \"tooltip\": {\n\
    \        \"shared\": true,\n        \"sort\": 0,\n        \"value_type\": \"individual\"\
    \n      },\n      \"type\": \"graph\",\n      \"xaxis\": {\n        \"buckets\"\
    : null,\n        \"mode\": \"time\",\n        \"name\": null,\n        \"show\"\
    : true,\n        \"values\": []\n      },\n      \"yaxes\": [\n        {\n   \
    \       \"format\": \"decbytes\",\n          \"label\": null,\n          \"logBase\"\
    : 1,\n          \"max\": null,\n          \"min\": null,\n          \"show\":\
    \ true\n        },\n        {\n          \"format\": \"short\",\n          \"\
    label\": null,\n          \"logBase\": 1,\n          \"max\": null,\n        \
    \  \"min\": null,\n          \"show\": true\n        }\n      ],\n      \"yaxis\"\
    : {\n        \"align\": false,\n        \"alignLevel\": null\n      }\n    }\n\
    \  ],\n  \"refresh\": \"30s\",\n  \"schemaVersion\": 16,\n  \"style\": \"dark\"\
    ,\n  \"tags\": [\"gloo\", \"dynamic\"],\n  \"time\": {\n    \"from\": \"now-15m\"\
    ,\n    \"to\": \"now\"\n  },\n  \"timepicker\": {\n    \"refresh_intervals\":\
    \ [\n      \"5s\",\n      \"10s\",\n      \"30s\",\n      \"1m\",\n      \"5m\"\
    ,\n      \"15m\",\n      \"30m\",\n      \"1h\",\n      \"2h\",\n      \"1d\"\n\
    \    ],\n    \"time_options\": [\n      \"5m\",\n      \"15m\",\n      \"1h\"\
    ,\n      \"6h\",\n      \"12h\",\n      \"24h\",\n      \"2d\",\n      \"7d\"\
    ,\n      \"30d\"\n    ]\n  }\n}"
  GRAFANA_URL: http://glooe-grafana.gloo-system.svc.cluster.local:80
kind: ConfigMap
metadata:
  labels:
    app: gloo
    release: glooe
  name: glooe-observability-config
  namespace: gloo-system
