---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auth-code-secret
  namespace: sso
secretDescriptor:
  backendType: secretsManager
  data:
  - key: qa1/sso/auth-code-secret
    name: auth-code-secret
    property: auth-code-secret

