---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-client-id
  namespace: sso
secretDescriptor:
  backendType: secretsManager
  data:
  - key: qa1/sso/google-client-id
    name: client-id
    property: client-id

