---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-service-account
  namespace: sso
secretDescriptor:
  backendType: secretsManager
  data:
  - key: qa1/sso/google-service-account
    name: service_account.json
    property: service_account.json

