---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: google-admin-email
  namespace: sso
secretDescriptor:
  backendType: secretsManager
  data:
  - key: qa1/sso/google-admin-email
    name: email
    property: email
  - key: qa1/sso/google-admin-email
    name: email-domain
    property: email-domain
  - key: qa1/sso/google-admin-email
    name: email-address
    property: email-address

