apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sso-auth
  labels:
    k8s-app: sso-auth
  namespace: sso
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: sso-auth
    spec:
      containers:
      - image: buzzfeed/sso:v2.1.0
        name: sso-auth
        command: ["/bin/sso-auth"]
        ports:
        - containerPort: 4180
        env:
          - name: PROVIDER_FIRST_GOOGLE_IMPERSONATE
            valueFrom:
              secretKeyRef:
                name: google-admin-email
                key: email
          - name: PROVIDER_FIRST_GOOGLE_CREDENTIALS
            value: /creds/service_account.json
          - name: AUTHORIZE_EMAIL_DOMAINS
            value: 'tidepool.org'
          - name: SERVER_HOST
            value: sso-auth.tidepool.org
          - name: AUTHORIZE_PROXY_DOMAINS
            value: tidepool.org
          - name: PROVIDER_FIRST_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google-client-id
                key: client-id
          - name: PROVIDER_FIRST_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: client-secret
          - name: CLIENT_PROXY_ID
            valueFrom:
              secretKeyRef:
                name: proxy-client-id
                key: proxy-client-id
          - name: CLIENT_PROXY_SECRET
            valueFrom:
              secretKeyRef:
                name: proxy-client-secret
                key: proxy-client-secret
          - name: SESSION_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-cookie-secret
                key: auth-cookie-secret
          - name: SESSION_KEY
            value: v3WI4ig2F18/VpSnAwik27HRxvfB9rsk38rCZ0mFtJw=
          - name: METRICS_STATSD_HOST
            value: localhost
          - name: METRICS_STATSD_PORT
            value: "11111"
          - name: SESSION_COOKIE_SECURE
            value: "false"
          - name: PROVIDER_FIRST_TYPE
            value: google
          - name: PROVIDER_FIRST_SLUG
            value: google

          - name: REDIRECT_URL
            value: https://sso-auth.tidepool.org
          - name: CLUSTER
            value: dev
          - name: VIRTUAL_HOST
            value: sso-auth.tidepool.org
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: google-service-account
            mountPath: /creds
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
