apiVersion: v1
kind: ConfigMap
metadata:
  name: upstream-configs
  namespace: sso
data:
  upstream_configs.yml: |-
    - service: dashboard
      default:
        from: dashboard-qa1.sso.tidepool.org
        to: http://linkerd-dashboard.linkerd.svc.cluster.local
        options:
          allowed_groups:
            - engineering@tidepool.org
