apiVersion: monitoring.coreos.com/v1alpha1
kind: PodMonitor
spec:
  podMetricsEndpoints:
  - path: /metrics
    targetPort: 8081
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
  namespaceSelector:
    any: true
