apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    k8s-app: linkerd-prometheus
    release: monitoring-prometheus-operator
  name: linkerd-federate
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    params:
      match[]:
      - '{job="linkerd-proxy"}'
      - '{job="linkerd-controller"}'
    path: /federate
    port: admin-http
    relabelings:
    - action: keep
      regex: ^prometheus$
      sourceLabels:
      - __meta_kubernetes_pod_container_name
    scrapeTimeout: 30s
  jobLabel: app
  namespaceSelector:
    matchNames:
    - linkerd
  selector:
    matchLabels:
      linkerd.io/control-plane-component: prometheus
