---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.13.0
  values:
    prometheus:
      prometheusSpec:
        replicas: 2      # work in High-Availability mode
        retention: 12h   # we only need a few hours of retenion, since the rest is uploaded to blob
        image:
          tag: "v2.8.0"    # use a specific version of Prometheus
        externalLabels:  # a cool way to add default labels to all metrics 
          region: {{ .Region }}
          cluster: {{ .ClusterName }}
          serviceMonitorNamespaceSelector:  # allows the operator to find target config from multiple namespaces
          any: true
        thanos:         # add Thanos Sidecar
          tag: v0.3.1   # a specific version of Thanos
          objectStorageConfig: # blob storage configuration to upload metrics 
            key: thanos.yaml
            name: thanos-objstore-config
    alertmanager:
      enabled: false
    grafana:           # (optional) we don't need Grafana in all clusters
      enabled: false
      defaultDashboardsEnabled: false
    nodeExporter:
      serviceMonitor:
        relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
