apiVersion: gloo.solo.io/v1
kind: Upstream
metadata: 
  name: gateway-proxy
  namespace: gloo-system
spec:
  kube:
    serviceName: gateway-proxy
    serviceNamespace: gloo-system
    servicePort: 80
