apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: pomerium-proxy
  namespace: pomerium
spec:
  discoveryMetadata: {}
  upstreamSpec:
    kube:
      selector:
        app.kubernetes.io/instance: pomerium
        app.kubernetes.io/name: pomerium-proxy
      serviceName: pomerium-proxy
      serviceNamespace: pomerium
      servicePort: 443
    sslConfig:
      secretRef:
        name: pomerium-proxy-tls
        namespace: pomerium
