---
apiVersion: v1
data:
  Scheme: "bW9uZ29kYg=="
  Addresses: "bW9uZ29kYg=="
  Username: ""
  Password: ""
  Database: ""
  Tls: "ZmFsc2U="
  OptParams: ""
kind: Secret
metadata:
  name: mongo
  namespace: qa2
type: Opaque
