apiVersion: v1
kind: Service
metadata:
  labels:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy-metrics
  namespace: gloo-system
spec:
  ports:
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
