apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: glooe-prometheus
    chart: prometheus-9.5.1
    component: alertmanager
    heritage: Helm
    release: glooe
  name: glooe-glooe-prometheus-alertmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glooe-glooe-prometheus-alertmanager
subjects:
- kind: ServiceAccount
  name: glooe-glooe-prometheus-alertmanager
  namespace: gloo-system
