apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: glooe-prometheus
    chart: prometheus-9.5.1
    component: server
    heritage: Helm
    release: glooe
  name: glooe-prometheus-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glooe-prometheus-server
subjects:
- kind: ServiceAccount
  name: glooe-prometheus-server
  namespace: gloo-system
