apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability-upstream-rolebinding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-upstream-role-default
subjects:
- kind: ServiceAccount
  name: observability
  namespace: gloo-system
