apiVersion: v1
data:
  config.yaml: |
    infinispan:
      clusterName: infinispan
    endpoints:
      hotrod:
        auth: false
        enabled: true
        serverName: infinispan
      rest:
        auth: false
        enabled: true
    jgroups:
      diagnostics: false
      encrypt: false
      transport: tcp
      dnsPing:
        query: "infinispan-ping.infinispan.svc.cluster.local"
  config-keycloak.xml: |
    <infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:infinispan:config:11.0" xmlns:server="urn:infinispan:server:11.0" xsi:schemaLocation="urn:infinispan:config:11.0 https://infinispan.org/schemas/infinispan-config-11.0.xsd urn:infinispan:server:11.0 https://infinispan.org/schemas/infinispan-server-11.0.xsd">
        <jgroups>
            <stack name="kube" extends="tcp">
                  <TCP bind_addr="${jgroups.bind.address,jgroups.tcp.address:SITE_LOCAL}"
                       bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"/>

                  <dns.DNS_PING dns_query="${jgroups.dns.query}" dns_record_type="A"
                                stack.combine="REPLACE" stack.position="MPING"/>
            </stack>
        </jgroups>
        <cache-container name="default" statistics="true">
            <transport cluster="${infinispan.cluster.name}" stack="kube"
                       node-name="${infinispan.node.name:}" lock-timeout="60000"/>
            <global-state/>
            <!-- BEGIN KEYCLOAK'S CACHES DEFINITION -->
            <replicated-cache-configuration name="keycloak-sessions" mode="SYNC" start="EAGER">
                <locking acquire-timeout="0" />
                <persistence>
                    <file-store shared="false" fetch-state="true" path="./keycloak">
                        <write-behind modification-queue-size="1024"/>
                    </file-store>
                </persistence>
            </replicated-cache-configuration>

            <replicated-cache name="work" configuration="keycloak-sessions" />
            <replicated-cache name="sessions" configuration="keycloak-sessions" />
            <replicated-cache name="offlineSessions" configuration="keycloak-sessions" />
            <replicated-cache name="actionTokens" configuration="keycloak-sessions" />
            <replicated-cache name="loginFailures" configuration="keycloak-sessions" />
            <replicated-cache name="clientSessions" configuration="keycloak-sessions" />
            <replicated-cache name="offlineClientSessions" configuration="keycloak-sessions" />
            <!-- END KEYCLOAK'S CACHES DEFINITION -->
        </cache-container>
        <server xmlns="urn:infinispan:server:11.0">
            <interfaces>
                <interface name="public">
                    <inet-address value="${infinispan.bind.address:SITE_LOCAL}"/>
                </interface>
            </interfaces>
            <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
                <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
            </socket-bindings>
            <security>
                <security-realms>
                    <security-realm name="default">
                        <properties-realm groups-attribute="Roles">
                            <user-properties path="users.properties" relative-to="infinispan.server.config.path" plain-text="true"/>
                            <group-properties path="groups.properties" relative-to="infinispan.server.config.path"/>
                        </properties-realm>
                    </security-realm>
                </security-realms>
            </security>
            <endpoints socket-binding="default">
                <hotrod-connector name="hotrod"/>
                <rest-connector name="rest"/>
            </endpoints>
        </server>
    </infinispan>
  jgroups-kube.xml: |
    <config xmlns="urn:org:jgroups"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.2.xsd"
            version="4.2.0">
        <TCP bind_addr="${jgroups.bind.address,jgroups.tcp.address:SITE_LOCAL}"
             bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"
             enable_diagnostics="false" thread_naming_pattern="pl" send_buf_size="640k" sock_conn_timeout="300"
             bundler_type="no-bundler" logical_addr_cache_expiration="360000" port_range="0"

             thread_pool.min_threads="${jgroups.thread_pool.min_threads:0}"
             thread_pool.max_threads="${jgroups.thread_pool.max_threads:200}"
             thread_pool.keep_alive_time="60000"
        />
        <kubernetes.KUBE_PING />
        <MERGE3 min_interval="10000" max_interval="30000"/>
        <FD_SOCK/>
        <!-- Suspect node `timeout` to `timeout + timeout_check_interval` millis after the last heartbeat -->
        <FD_ALL timeout="10000"
                interval="2000"
                timeout_check_interval="1000"
        />
        <VERIFY_SUSPECT timeout="1000"/>
        <pbcast.NAKACK2 use_mcast_xmit="false" xmit_interval="100" xmit_table_num_rows="50"
                        xmit_table_msgs_per_row="1024" xmit_table_max_compaction_time="30000" resend_last_seqno="true"/>
        <UNICAST3 xmit_interval="100" xmit_table_num_rows="50" xmit_table_msgs_per_row="1024"
                  xmit_table_max_compaction_time="30000"/>
        <pbcast.STABLE stability_delay="500" desired_avg_gossip="5000" max_bytes="1M"/>
        <pbcast.GMS print_local_addr="false" join_timeout="${jgroups.join_timeout:2000}"/>
        <UFC max_credits="4m" min_threshold="0.40"/>
        <MFC max_credits="4m" min_threshold="0.40"/>
        <FRAG3/>
    </config>
kind: ConfigMap
metadata:
  name: infinispan
  namespace: infinispan
