apiVersion: v1
kind: ServiceAccount
metadata:
  name: infinispan
  namespace: infinispan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infinispan-view
  namespace: infinispan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: infinispan
    namespace: infinispan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infiniband-viewer
  namespace: infinispan
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
