apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infinispan-server
  namespace: infinispan
  labels:
    app: infinispan-server
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  serviceName: infinispan-server-headless
  selector:
    matchLabels:
      app: infinispan-server
  template:
    metadata:
      labels:
        app: infinispan-server
      name: infinispan-server
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: infinispan
      initContainers:
        - name: copy-config
          image: busybox
          command: ["sh", "-c", "cp /config-ro/* /config/; chown 1000 /config/* ; chmod g+w /config/*"]
          volumeMounts:
            - name: configtmp
              mountPath: "/config"
            - name: config
              mountPath: /config-ro/config-keycloak.xml
              subPath: config-keycloak.xml
            - name: config
              mountPath: /config-ro/config.yaml
              subPath: config.yaml
            - name: config
              mountPath: /config-ro/jgroups-kube.xml
              subPath: jgroups-kube.xml
      containers:
        - env:
            - name: JAVA_OPTS_EXTRA
              value: "-Dinfinispan.cluster.stack=kube -Dinfinispan.node.name=$(POD_NAME) -Djboss.tx.node.id=$(POD_NAME) -Dinfinispan.cluster.name=$(KUBERNETES_NAMESPACE) "
            - name: KUBERNETES_LABELS
              value: app=infinispan-server
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_USER
              value: "admin"
            - name: APP_PASS
              value: "admin"
            - name: MGMT_USER
              value: admin
            - name: MGMT_PASS
              value: admin
          command:
            - "/opt/infinispan/bin/server.sh"
          args:
            - "-Djgroups.dns.query=infinispan-ping.infinispan.svc.cluster.local"
            - "-c"
            - "/opt/infinispan/server/conf/config-keycloak.xml"
          image: infinispan/server:11.0.4.Final
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: rest/v2/cache-managers/default/health/status
              port: 11222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 80
          name: infinispan-server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9990
              name: management
              protocol: TCP
            - containerPort: 8888
              name: ping
              protocol: TCP
            - containerPort: 11222
              name: hotrod
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: rest/v2/cache-managers/default/health/status
              port: 11222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 80
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: configtmp
              mountPath: /opt/infinispan/server/conf/config-keycloak.xml
              subPath: config-keycloak.xml
            - name: configtmp
              mountPath: /opt/infinispan/server/conf/jgroups-kube.xml
              subPath: jgroups-kube.xml
            - name: configtmp
              mountPath: /opt/infinispan/server/conf/config.yaml
              subPath: config.yaml
            - name: data
              mountPath: "/opt/infinispan/server/data"
      terminationGracePeriodSeconds: 120
      volumes:
        - name: config
          configMap:
            name: infinispan
        - name: configtmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Hot Rod's port.
  labels:
    app: infinispan-server
  name: infinispan-server-hotrod
  namespace: infinispan
spec:
  ports:
    - port: 11222
      targetPort: 11222
  selector:
    app: infinispan-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's HTTP port.
  labels:
    app: infinispan-server
  name: infinispan-server-http
  namespace: infinispan
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: infinispan-server
---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-server-headless
  namespace: infinispan
  labels:
    app: infinispan-server
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - port: 11222
      targetPort: 11222
      protocol: TCP
      name: hotrod
  selector:
    app: infinispan-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan-server
  name: infinispan-ping
  namespace: infinispan
spec:
  clusterIP: None
  ports:
    - name: ping
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: infinispan-server
  sessionAffinity: None
  type: ClusterIP
