apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability-upstream-role-default
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - upstreams
  - settings
  verbs:
  - get
  - list
  - watch
