apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: glooe-prometheus
    chart: prometheus-9.5.1
    component: kube-state-metrics
    heritage: Helm
    release: glooe
  name: glooe-prometheus-kube-state-metrics
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glooe-prometheus
      component: kube-state-metrics
      release: glooe
  template:
    metadata:
      labels:
        app: glooe-prometheus
        chart: prometheus-9.5.1
        component: kube-state-metrics
        heritage: Helm
        release: glooe
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v1.6.0
        imagePullPolicy: IfNotPresent
        name: glooe-prometheus-kube-state-metrics
        ports:
        - containerPort: 8080
          name: metrics
        resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: glooe-prometheus-kube-state-metrics
