---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-tool
  name: admin-tool
  namespace: admin-system
spec:
  selector:
    matchLabels:
      app: admin-tool
  template:
    metadata:
      labels:
        app: admin-tool
    spec:
      containers:
      - image: tidepool/admin-tool:latest
        name: admin-tool
        ports:
        - containerPort: 8080
