#!/bin/bash

cd /tmp
curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/1.2.0.Final/debezium-connector-mongodb-1.2.0.Final-plugin.tar.gz | tar xvz

cat <<EOF >Dockerfile
FROM strimzi/kafka/0.18.0-rc1-kafka-2.5.0
USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium
COPY ./debezium-connector-mongodb/ /opt/kafka/plugins/debezium/
USER 1001
EOF

export DOCKER_ORG=tidepool
docker build . -t ${DOCKER_ORG}/connect-debezium
docker push ${DOCKER_ORG}/connect-debezium
