#!/bin/bash
# Usage:
#   helmit template ${file:-helmrelease.yaml} - expand template for HelmRelease
#   helmit install ${file:-helmrelease.yaml} - install HelmRelease
#   helmit delete ${file:-helmrelease.yaml} - delete HelmRelease
#   helmit cmp ${file:-helmrelease.yaml} [$file2] - compare expanded HelmRelease outputs, if file2 is not given, extract from cluster

TMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'TMP_DIR')

if [ ! -f /usr/local/bin/dyff ]
then
  brew install dyff
fi

# clean up all temporary files
function cleanup() {
  if [ -f "$TMP_DIR" ]; then
    cd /
    rm -rf $TMP_DIR
  fi
}

trap cleanup EXIT

op=$1
shift

if [ "$#" -eq 0 ]
then
  file=helmrelease.yaml
else
  file=$1
  shift
fi

if [ ! -f "$file" ]
then
  echo "Helmrelease file $file not found"
  exit 1
fi

function get_value() {
  local hr=$1
  echo "$hr" | jq "$2" | sed -e 's/"//g'
}

function get_release() {
  get_value "$1" ".spec.releaseName"
}

function get_name() {
  get_value "$1" ".spec.chart.name"
}

function get_namespace() {
  get_value "$1" ".metadata.namespace"
}

function get_version() {
  get_value "$1" ".spec.chart.version"
}

function get_git() {
  get_value "$1" ".spec.chart.git"
}

function get_path() {
  get_value "$1" ".spec.chart.path"
}

function get_ref() {
  get_value "$1" ".spec.chart.ref"
}

function get_values() {
  local hr=$1
  echo "$hr" | jq '.spec.values' | yq r - 
}

function get_repository() {
  get_value "$1" ".spec.chart.repository"
}

function load_chart() {
  local name=$1
  local repo=$2
  helm repo add $name $repo >/dev/null 2>&1
  helm repo update >/dev/null 2>&1
}

hr=$(yq r $file -j)
name=$(get_name "$hr")
namespace=$(get_namespace "$hr")

version=$(get_version "$hr")
if [ -z "$version" ]
then
  git=$(get_git)
  ref=$(get_ref)
  path=$(get_path)
else
  release=$(get_release "$hr")
  release=${release:=${name}}
  repo=$(get_repository "$hr")
fi

function show() {
  echo "---"
  echo "# $1"
  cat $1
}

case $op in
show)
  show $file
  ;;
install)
  echo "installing $file" >/dev/stderr
  show $file >/dev/stderr 
  load_chart $name $repo
  get_values "$hr" >/tmp/${name}-${namespace}.yaml
  kubectl create namespace $namespace 2>/dev/null
  op="upgrade -i --version $version -f /tmp/${name}-${namespace}.yaml"
  helm $op $release $name/$name --namespace ${namespace} 
  ;;
delete)
  echo "deleting $file" >/dev/stderr
  show $file >/dev/stderr 
  load_chart $name $repo
  echo "deleting" >/dev/stderr
  show $file >/dev/stderr
  helm delete $release $name/$name --namespace ${namespace} 
  ;;
template)
  echo "templating $file" >/dev/stderr
  show $file >/dev/stderr 
  load_chart $name $repo
  get_values "$hr" >/tmp/${name}-${namespace}.yaml
  op="template --version $version -f /tmp/${name}-${namespace}.yaml"
  helm $op $release $name/$name --namespace ${namespace} 
  ;;
get)
  echo "getting in cluster $namespace/$name"
  tmp=/tmp/$name-$namespace-$release
  kubectl get helmrelease -n $namespace $name -o yaml > $tmp
  show $tmp
  ;;
source)
  helm pull $name/$name --version $version --untar
  ;;
cmp)
  if [ "$#" -eq 0 ]
  then
    tmp=/tmp/$name-$namespace-$release
    kubectl get helmrelease -n $namespace $name -o yaml | yq d - 'metadata.annotations."kubectl.kubernetes.io/last-applied-configuration"'  | yq d - 'status'> $tmp
    file2=$file
    file=$tmp
  else
    file2=$1
  fi
  echo "=== HelmRelease Differences ==="
  #yamldiff --file1 $file --file2 $file2
  dyff between $file $file2 2>/dev/null
  echo "=== Helm Template Differences ==="

  helmit template $file 2>/dev/null | separate_files $TMP_DIR/left >$TMP_DIR/leftlist
  helmit template $file2 2>/dev/null | separate_files $TMP_DIR/right >$TMP_DIR/rightlist

  cd $TMP_DIR
  grc diff leftlist rightlist
  echo "== Resources Changed ==="
  for file in $(find left)
  do
    base=${file#left/}
    if [ -f right/$base ]
    then
      dyff between left/$base right/$base 2>/dev/null
    fi
  done
  ;;
esac
