#!/bin/bash

cat <<EOF >Dockerfile
FROM strimzi/kafka:0.18.0-kafka-2.5.0
USER root
RUN mkdir -p /opt/kafka/plugins/debezium-connector-mongodb
RUN mkdir -p /opt/kafka/extlibs
ENV CLASSPATH=/opt/kafka/extlibs/*
RUN curl -sL "https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/1.2.0.Final/debezium-connector-mongodb-1.2.0.Final-plugin.tar.gz" | tar xz -C /tmp && cp -r /tmp/debezium-connector-mongodb/* /opt/kafka/plugins/debezium-connector-mongodb/
RUN curl -sL "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz" | tar xz -C /tmp && cp -r /tmp/graalvm-ce-java11-20.1.0/lib/graalvm/* /opt/kafka/extlibs/
RUN chown -R 1001 /opt/kafka/plugins
RUN chown -R 1001 /opt/kafka/extlibs
USER 1001
EOF

export DOCKER_ORG=tidepool
docker build . -t ${DOCKER_ORG}/connect-debezium:0.3.9
docker push ${DOCKER_ORG}/connect-debezium:0.3.9
