#!/usr/local/bin/python3
#
# Select items of a particular kind
#
# Usage: $0 ${KIND}
#

import sys
import yaml

input = yaml.safe_load_all(sys.stdin)

for value in input:
    if value != None and "kind" in value and value["kind"] == sys.argv[1]:
        print('---')
        yaml.dump(value, stream=sys.stdout, encoding='utf-8')
