---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcloud
  namespace: flux
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: fluxcloud
  chart:
    git: git@github.com:tidepool-org/development
    path: charts/fluxcloud/0.1.0
    ref: k8s
  values:
    name: fluxcloud
    github: "https://github.com/tidepool-org/cluster-{{ .ClusterName }}"
    slack:
      channel: "#flux-{{ .ClusterName }}"
      username: derrickburns
