apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: glooe-prometheus
    chart: prometheus-9.5.1
    component: kube-state-metrics
    heritage: Helm
    release: glooe
  name: glooe-prometheus-kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glooe-prometheus-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: glooe-prometheus-kube-state-metrics
  namespace: gloo-system
