apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  chart:
    git: git@github.com:godaddy/kubernetes-external-secrets
    path: charts/kubernetes-external-secrets
    ref: master
  values:
    fullnameOverride: external-secrets
    serviceAccount:
      create: false
      name: external-secrets
    image:
      repository: tidepool/external-secrets
      tag: iam2
