apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongomirror
  namespace: mongomirror
  labels:
    app: mongomirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongomirror
  template:
    metadata:
      labels:
        app: mongomirror
    spec:
      containers:
      - env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: HOST
        - name: DESTINATION
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION
        - name: DESTINATION_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION_USERNAME
        - name: DESTINATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION_PASSWORD
        image: tidepool/mongomirror:latest
        name: mongomirror
        volumeMounts:
        - name: certs
          mountPath: "/tmp/certs"
          readOnly: true
        command: ["/mongomirror/bin/mongomirror"]
        ports:
        - containerPort: 8080
        args: [ "--host", "$(HOST)", "--ssl", "--destination", "$(DESTINATION)", "--destinationUsername", "$(DESTINATION_USERNAME)", "--destinationPassword", "$(DESTINATION_PASSWORD)", "--sslCAFile", "/tmp/certs/ca.crt", "--drop", "--httpStatusPort", "8080", "--bookmarkFile", "/bookmark/mongomirror.timestamp" ]
      restartPolicy: Always
      volumes:
      - name: certs
        secret:
          secretName: mongomirror
