---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongomirror
  namespace: mongomirror
  annotations:
    secretmap.reloader.stakater.com/reload: "mongomirror"
spec:
  selector:
    matchLabels:
      app: mongomirror
      app.kubernetes.io/name: mongomirror
      app.kubernetes.io/instance: mongomirror
  replicas: 1
  template:
    metadata:
      labels:
        app: mongomirror
        app.kubernetes.io/name: mongomirror
        app.kubernetes.io/instance: mongomirror
    spec:
      containers:
      - env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: HOST
        - name: DESTINATION
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION
        - name: DESTINATION_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION_USERNAME
        - name: DESTINATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongomirror
              key: DESTINATION_PASSWORD
        image: tidepool/mongomirror:latest
        name: mongomirror
        volumeMounts:
        - name: foo
          mountPath: "/etc/ssl/certs"
          readOnly: true
        command: ["mongomirror"]
        args: [ "--host", "$(HOST)", "--ssl", "--destination", "$(DESTINATION)", "--destinationUsername", "$(DESTINATION_USERNAME)", "--destinationPassword", "$(DESTINATION_PASSWORD)", "--sslCAFile", "/etc/ssl/certs/ca.crt", "--drop" ]
      restartPolicy: Always
      volumes:
      - name: mongomirror
        secret:
          secretName: mongomirror
