apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookmark
  namespace: mongomirror
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Mi
